version: 0.1
phases:
    install:
      commands:
        - apt-get update && apt-get -y install python-pip
        - ls /root/.cache/pip/*/*
        - pip list
        - pip install --upgrade python
        - pip install --upgrade awscli
    pre_build:
      commands:
        - printenv
        - echo -n "$BUILD_TAG" > /tmp/build_id.out
        - printf "%s:%s" "$REPOSITORY_URI" "$(cat /tmp/build_id.out)" > /tmp/build_tag.out
        - printf '{"tag":"%s"}' "$(cat /tmp/build_id.out)" > /tmp/build.json
        - $(aws ecr get-login --no-include-email)
    build:
      commands:
        - docker build --tag "$(cat /tmp/build_tag.out)" .
    post_build:
      commands:
        - docker push "$(cat /tmp/build_tag.out)"
cache:
  paths:
    # Debian package caches, so we don't need to keep redownloading debian packages:
    - /var/cache/apt/**/*
    - /var/lib/apt/lists/**/*
    - /root/.cache/pip/**/*
artifacts:
  files: /tmp/build.json
  discard-paths: yes
